In [2]:
# imports 
import pandas as pd

In [3]:
raw_dataset = pd.read_csv("./testdata/Gediplomeerden__onderwijssoort__woonregio_13022024_132550.csv", skiprows=5, sep=";")

raw_dataset.head()

,Unnamed: 0,Nederland,Noord-Nederland (LD),Oost-Nederland (LD),West-Nederland (LD),Zuid-Nederland (LD),Niet in te delen (LD),Groningen (PV),Fryslân (PV),Drenthe (PV),...,Noord-Holland (PV),Zuid-Holland (PV),Zeeland (PV),Noord-Brabant (PV),Limburg (PV),Niet in te delen (PV),Vier grootste gemeenten,Meer dan 100 000 inwoners (exclusief G4),Minder dan 100 000 inwoners,Niet in te delen
0,Onderwijssoort,aantal,aantal,aantal,aantal,aantal,aantal,aantal,aantal,aantal,...,aantal,aantal,aantal,aantal,aantal,aantal,aantal,aantal,aantal,aantal
1,Totaal voortgezet onderwijs (vo),167410,16200,38620,78840,33410,340,4700,6490,5020,...,26400,34640,3600,24480,8930,340,18340,37650,111070,340
2,Vwo,35610,2830,6970,18980,6760,70,960,1060,810,...,6650,7750,610,4920,1840,70,4660,8330,22550,70
3,Havo,45410,4340,10450,21400,9140,90,1230,1830,1280,...,7400,8910,1060,6760,2380,90,4530,10320,30470,90
4,Vmbo g/t,47340,4760,11140,21490,9840,120,1330,1940,1490,...,6950,9930,1070,7290,2540,120,4660,10710,31850,120

In [4]:
with_renamed_column = raw_dataset.rename(columns={"Unnamed: 0":"Onderwijssoort"})
with_renamed_column.head()

,Onderwijssoort,Nederland,Noord-Nederland (LD),Oost-Nederland (LD),West-Nederland (LD),Zuid-Nederland (LD),Niet in te delen (LD),Groningen (PV),Fryslân (PV),Drenthe (PV),...,Noord-Holland (PV),Zuid-Holland (PV),Zeeland (PV),Noord-Brabant (PV),Limburg (PV),Niet in te delen (PV),Vier grootste gemeenten,Meer dan 100 000 inwoners (exclusief G4),Minder dan 100 000 inwoners,Niet in te delen
0,Onderwijssoort,aantal,aantal,aantal,aantal,aantal,aantal,aantal,aantal,aantal,...,aantal,aantal,aantal,aantal,aantal,aantal,aantal,aantal,aantal,aantal
1,Totaal voortgezet onderwijs (vo),167410,16200,38620,78840,33410,340,4700,6490,5020,...,26400,34640,3600,24480,8930,340,18340,37650,111070,340
2,Vwo,35610,2830,6970,18980,6760,70,960,1060,810,...,6650,7750,610,4920,1840,70,4660,8330,22550,70
3,Havo,45410,4340,10450,21400,9140,90,1230,1830,1280,...,7400,8910,1060,6760,2380,90,4530,10320,30470,90
4,Vmbo g/t,47340,4760,11140,21490,9840,120,1330,1940,1490,...,6950,9930,1070,7290,2540,120,4660,10710,31850,120

In [5]:
deleted_first_row_data = with_renamed_column.iloc[1:]
deleted_first_row_data.head()

,Onderwijssoort,Nederland,Noord-Nederland (LD),Oost-Nederland (LD),West-Nederland (LD),Zuid-Nederland (LD),Niet in te delen (LD),Groningen (PV),Fryslân (PV),Drenthe (PV),...,Noord-Holland (PV),Zuid-Holland (PV),Zeeland (PV),Noord-Brabant (PV),Limburg (PV),Niet in te delen (PV),Vier grootste gemeenten,Meer dan 100 000 inwoners (exclusief G4),Minder dan 100 000 inwoners,Niet in te delen
1,Totaal voortgezet onderwijs (vo),167410,16200,38620,78840,33410,340,4700,6490,5020,...,26400,34640,3600,24480,8930,340,18340,37650,111070,340
2,Vwo,35610,2830,6970,18980,6760,70,960,1060,810,...,6650,7750,610,4920,1840,70,4660,8330,22550,70
3,Havo,45410,4340,10450,21400,9140,90,1230,1830,1280,...,7400,8910,1060,6760,2380,90,4530,10320,30470,90
4,Vmbo g/t,47340,4760,11140,21490,9840,120,1330,1940,1490,...,6950,9930,1070,7290,2540,120,4660,10710,31850,120
5,Vmbo-k,24870,2840,6590,10500,4890,40,750,1080,1010,...,3460,4880,550,3530,1370,40,2670,5280,16870,40

In [6]:
deleted_first_row_data

,Onderwijssoort,Nederland,Noord-Nederland (LD),Oost-Nederland (LD),West-Nederland (LD),Zuid-Nederland (LD),Niet in te delen (LD),Groningen (PV),Fryslân (PV),Drenthe (PV),...,Noord-Holland (PV),Zuid-Holland (PV),Zeeland (PV),Noord-Brabant (PV),Limburg (PV),Niet in te delen (PV),Vier grootste gemeenten,Meer dan 100 000 inwoners (exclusief G4),Minder dan 100 000 inwoners,Niet in te delen
1,Totaal voortgezet onderwijs (vo),167410,16200,38620,78840,33410,340,4700,6490,5020,...,26400,34640,3600,24480,8930,340,18340,37650,111070,340
2,Vwo,35610,2830,6970,18980,6760,70,960,1060,810,...,6650,7750,610,4920,1840,70,4660,8330,22550,70
3,Havo,45410,4340,10450,21400,9140,90,1230,1830,1280,...,7400,8910,1060,6760,2380,90,4530,10320,30470,90
4,Vmbo g/t,47340,4760,11140,21490,9840,120,1330,1940,1490,...,6950,9930,1070,7290,2540,120,4660,10710,31850,120
5,Vmbo-k,24870,2840,6590,10500,4890,40,750,1080,1010,...,3460,4880,550,3530,1370,40,2670,5280,16870,40
6,Vmbo-b,14180,1430,3470,6470,2790,20,430,580,430,...,1940,3180,310,1990,800,20,1820,3010,9330,20
7,Totaal vavo,5250,460,1200,2560,1010,10,150,190,130,...,990,1060,90,690,320,10,780,1480,2980,10
8,Vavo vwo,1560,160,340,770,290,0,50,70,40,...,340,260,30,210,90,0,250,410,900,0
9,Vavo havo,3050,270,700,1470,600,10,90,100,80,...,550,640,60,410,190,10,470,850,1730,10
10,Vavo vmbo-t,640,40,160,330,110,0,10,20,10,...,100,170,10,70,50,0,70,220,350,0
11,Totaal mbo (incl. extranei),152040,17960,37200,66260,29820,800,5610,7130,5230,...,21920,30910,3530,21380,8440,800,17330,34630,99280,800
12,Entreeopleiding (incl.extranei),11500,1210,2290,6000,1900,100,350,520,340,...,2090,3000,230,1350,550,100,2370,2900,6130,100
13,Niveau 2 (inclusief extranei),33950,3770,8470,15420,6140,140,1240,1430,1110,...,5150,7270,790,4420,1720,140,4630,7680,21500,140
14,Niveau 3 (inclusief extranei),34040,4500,9030,13580,6760,170,1340,1910,1250,...,4430,6330,950,4840,1930,170,2750,7020,24110,170
15,Niveau 4 (inclusief extranei),72540,8480,17400,31260,15020,390,2670,3270,2530,...,10250,14300,1560,10780,4240,390,7580,17030,47550,390
16,Hbo-associate degree,5120,550,1160,1860,1500,50,160,220,170,...,400,1000,150,1260,240,50,460,1290,3330,50
17,Hbo-bachelor,66450,7060,14440,28500,14130,2330,3300,2340,1420,...,9670,12590,1060,10240,3890,2330,10340,19910,33870,2330
18,Hbo-master/vervolgopleiding,4670,500,820,2040,870,440,230,190,80,...,720,870,50,650,220,440,1080,1340,1820,440
19,Wo-bachelor,41640,4020,5850,22440,6570,2760,3440,330,250,...,7580,10490,250,3960,2610,2760,11580,15950,11340,2760
20,Wo-master,51590,3830,6880,26660,7360,6870,3080,470,280,...,9580,11930,160,4980,2390,6870,15950,17060,11710,6870
21,Bron: CBS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
last_row_deleted = deleted_first_row_data.iloc[:-1]
last_row_deleted

,Onderwijssoort,Nederland,Noord-Nederland (LD),Oost-Nederland (LD),West-Nederland (LD),Zuid-Nederland (LD),Niet in te delen (LD),Groningen (PV),Fryslân (PV),Drenthe (PV),...,Noord-Holland (PV),Zuid-Holland (PV),Zeeland (PV),Noord-Brabant (PV),Limburg (PV),Niet in te delen (PV),Vier grootste gemeenten,Meer dan 100 000 inwoners (exclusief G4),Minder dan 100 000 inwoners,Niet in te delen
1,Totaal voortgezet onderwijs (vo),167410,16200,38620,78840,33410,340,4700,6490,5020,...,26400,34640,3600,24480,8930,340,18340,37650,111070,340
2,Vwo,35610,2830,6970,18980,6760,70,960,1060,810,...,6650,7750,610,4920,1840,70,4660,8330,22550,70
3,Havo,45410,4340,10450,21400,9140,90,1230,1830,1280,...,7400,8910,1060,6760,2380,90,4530,10320,30470,90
4,Vmbo g/t,47340,4760,11140,21490,9840,120,1330,1940,1490,...,6950,9930,1070,7290,2540,120,4660,10710,31850,120
5,Vmbo-k,24870,2840,6590,10500,4890,40,750,1080,1010,...,3460,4880,550,3530,1370,40,2670,5280,16870,40
6,Vmbo-b,14180,1430,3470,6470,2790,20,430,580,430,...,1940,3180,310,1990,800,20,1820,3010,9330,20
7,Totaal vavo,5250,460,1200,2560,1010,10,150,190,130,...,990,1060,90,690,320,10,780,1480,2980,10
8,Vavo vwo,1560,160,340,770,290,0,50,70,40,...,340,260,30,210,90,0,250,410,900,0
9,Vavo havo,3050,270,700,1470,600,10,90,100,80,...,550,640,60,410,190,10,470,850,1730,10
10,Vavo vmbo-t,640,40,160,330,110,0,10,20,10,...,100,170,10,70,50,0,70,220,350,0
11,Totaal mbo (incl. extranei),152040,17960,37200,66260,29820,800,5610,7130,5230,...,21920,30910,3530,21380,8440,800,17330,34630,99280,800
12,Entreeopleiding (incl.extranei),11500,1210,2290,6000,1900,100,350,520,340,...,2090,3000,230,1350,550,100,2370,2900,6130,100
13,Niveau 2 (inclusief extranei),33950,3770,8470,15420,6140,140,1240,1430,1110,...,5150,7270,790,4420,1720,140,4630,7680,21500,140
14,Niveau 3 (inclusief extranei),34040,4500,9030,13580,6760,170,1340,1910,1250,...,4430,6330,950,4840,1930,170,2750,7020,24110,170
15,Niveau 4 (inclusief extranei),72540,8480,17400,31260,15020,390,2670,3270,2530,...,10250,14300,1560,10780,4240,390,7580,17030,47550,390
16,Hbo-associate degree,5120,550,1160,1860,1500,50,160,220,170,...,400,1000,150,1260,240,50,460,1290,3330,50
17,Hbo-bachelor,66450,7060,14440,28500,14130,2330,3300,2340,1420,...,9670,12590,1060,10240,3890,2330,10340,19910,33870,2330
18,Hbo-master/vervolgopleiding,4670,500,820,2040,870,440,230,190,80,...,720,870,50,650,220,440,1080,1340,1820,440
19,Wo-bachelor,41640,4020,5850,22440,6570,2760,3440,330,250,...,7580,10490,250,3960,2610,2760,11580,15950,11340,2760
20,Wo-master,51590,3830,6880,26660,7360,6870,3080,470,280,...,9580,11930,160,4980,2390,6870,15950,17060,11710,6870

In [8]:
df = last_row_deleted
df.head()

,Onderwijssoort,Nederland,Noord-Nederland (LD),Oost-Nederland (LD),West-Nederland (LD),Zuid-Nederland (LD),Niet in te delen (LD),Groningen (PV),Fryslân (PV),Drenthe (PV),...,Noord-Holland (PV),Zuid-Holland (PV),Zeeland (PV),Noord-Brabant (PV),Limburg (PV),Niet in te delen (PV),Vier grootste gemeenten,Meer dan 100 000 inwoners (exclusief G4),Minder dan 100 000 inwoners,Niet in te delen
1,Totaal voortgezet onderwijs (vo),167410,16200,38620,78840,33410,340,4700,6490,5020,...,26400,34640,3600,24480,8930,340,18340,37650,111070,340
2,Vwo,35610,2830,6970,18980,6760,70,960,1060,810,...,6650,7750,610,4920,1840,70,4660,8330,22550,70
3,Havo,45410,4340,10450,21400,9140,90,1230,1830,1280,...,7400,8910,1060,6760,2380,90,4530,10320,30470,90
4,Vmbo g/t,47340,4760,11140,21490,9840,120,1330,1940,1490,...,6950,9930,1070,7290,2540,120,4660,10710,31850,120
5,Vmbo-k,24870,2840,6590,10500,4890,40,750,1080,1010,...,3460,4880,550,3530,1370,40,2670,5280,16870,40

In [9]:
df.to_pickle("./saved_clean_data.pkl")

In [11]:
unpickled_df = pd.read_pickle("./saved_clean_data.pkl")
unpickled_df.head()

,Onderwijssoort,Nederland,Noord-Nederland (LD),Oost-Nederland (LD),West-Nederland (LD),Zuid-Nederland (LD),Niet in te delen (LD),Groningen (PV),Fryslân (PV),Drenthe (PV),...,Noord-Holland (PV),Zuid-Holland (PV),Zeeland (PV),Noord-Brabant (PV),Limburg (PV),Niet in te delen (PV),Vier grootste gemeenten,Meer dan 100 000 inwoners (exclusief G4),Minder dan 100 000 inwoners,Niet in te delen
1,Totaal voortgezet onderwijs (vo),167410,16200,38620,78840,33410,340,4700,6490,5020,...,26400,34640,3600,24480,8930,340,18340,37650,111070,340
2,Vwo,35610,2830,6970,18980,6760,70,960,1060,810,...,6650,7750,610,4920,1840,70,4660,8330,22550,70
3,Havo,45410,4340,10450,21400,9140,90,1230,1830,1280,...,7400,8910,1060,6760,2380,90,4530,10320,30470,90
4,Vmbo g/t,47340,4760,11140,21490,9840,120,1330,1940,1490,...,6950,9930,1070,7290,2540,120,4660,10710,31850,120
5,Vmbo-k,24870,2840,6590,10500,4890,40,750,1080,1010,...,3460,4880,550,3530,1370,40,2670,5280,16870,40