In [45]:
import pandas as pd
from pandas import testing as tm
df = pd.read_pickle("./data.pkl")
df.head()

,Onderwijssoort,Nederland,Noord-Nederland (LD),Oost-Nederland (LD),West-Nederland (LD),Zuid-Nederland (LD),Niet in te delen (LD),Groningen (PV),Fryslân (PV),Drenthe (PV),...,Noord-Holland (PV),Zuid-Holland (PV),Zeeland (PV),Noord-Brabant (PV),Limburg (PV),Niet in te delen (PV),Vier grootste gemeenten,Meer dan 100 000 inwoners (exclusief G4),Minder dan 100 000 inwoners,Niet in te delen
1,Totaal voortgezet onderwijs (vo),167410,16200,38620,78840,33410,340,4700,6490,5020,...,26400,34640,3600,24480,8930,340,18340,37650,111070,340
2,Vwo,35610,2830,6970,18980,6760,70,960,1060,810,...,6650,7750,610,4920,1840,70,4660,8330,22550,70
3,Havo,45410,4340,10450,21400,9140,90,1230,1830,1280,...,7400,8910,1060,6760,2380,90,4530,10320,30470,90
4,Vmbo g/t,47340,4760,11140,21490,9840,120,1330,1940,1490,...,6950,9930,1070,7290,2540,120,4660,10710,31850,120
5,Vmbo-k,24870,2840,6590,10500,4890,40,750,1080,1010,...,3460,4880,550,3530,1370,40,2670,5280,16870,40

In [46]:
indexed_df = df.set_index(['Onderwijssoort'])
indexed_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, Totaal voortgezet onderwijs (vo) to Wo-master
Data columns (total 23 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Nederland                                 20 non-null     object
 1   Noord-Nederland (LD)                      20 non-null     object
 2   Oost-Nederland (LD)                       20 non-null     object
 3   West-Nederland (LD)                       20 non-null     object
 4   Zuid-Nederland (LD)                       20 non-null     object
 5   Niet in te delen (LD)                     20 non-null     object
 6   Groningen (PV)                            20 non-null     object
 7   Fryslân (PV)                              20 non-null     object
 8   Drenthe (PV)                              20 non-null     object
 9   Overijssel (PV)                           20 non-null     object
 10  Flevoland (PV)                            20 non-null     object
 11  Gelderland (PV)                           20 non-null     object
 12  Utrecht (PV)                              20 non-null     object
 13  Noord-Holland (PV)                        20 non-null     object
 14  Zuid-Holland (PV)                         20 non-null     object
 15  Zeeland (PV)                              20 non-null     object
 16  Noord-Brabant (PV)                        20 non-null     object
 17  Limburg (PV)                              20 non-null     object
 18  Niet in te delen (PV)                     20 non-null     object
 19  Vier grootste gemeenten                   20 non-null     object
 20  Meer dan 100 000 inwoners (exclusief G4)  20 non-null     object
 21  Minder dan 100 000 inwoners               20 non-null     object
 22  Niet in te delen                          20 non-null     object
dtypes: object(23)
memory usage: 3.8+ KB

In [47]:
def reset_known_index(df, column_name):
    reset_index = df.set_index([column_name])
    return reset_index

test_reset_known_index = reset_known_index(df, 'Onderwijssoort')
test_reset_known_index.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, Totaal voortgezet onderwijs (vo) to Wo-master
Data columns (total 23 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Nederland                                 20 non-null     object
 1   Noord-Nederland (LD)                      20 non-null     object
 2   Oost-Nederland (LD)                       20 non-null     object
 3   West-Nederland (LD)                       20 non-null     object
 4   Zuid-Nederland (LD)                       20 non-null     object
 5   Niet in te delen (LD)                     20 non-null     object
 6   Groningen (PV)                            20 non-null     object
 7   Fryslân (PV)                              20 non-null     object
 8   Drenthe (PV)                              20 non-null     object
 9   Overijssel (PV)                           20 non-null     object
 10  Flevoland (PV)                            20 non-null     object
 11  Gelderland (PV)                           20 non-null     object
 12  Utrecht (PV)                              20 non-null     object
 13  Noord-Holland (PV)                        20 non-null     object
 14  Zuid-Holland (PV)                         20 non-null     object
 15  Zeeland (PV)                              20 non-null     object
 16  Noord-Brabant (PV)                        20 non-null     object
 17  Limburg (PV)                              20 non-null     object
 18  Niet in te delen (PV)                     20 non-null     object
 19  Vier grootste gemeenten                   20 non-null     object
 20  Meer dan 100 000 inwoners (exclusief G4)  20 non-null     object
 21  Minder dan 100 000 inwoners               20 non-null     object
 22  Niet in te delen                          20 non-null     object
dtypes: object(23)
memory usage: 3.8+ KB

In [48]:
test_reset_known_index.index

Index(['Totaal voortgezet onderwijs (vo)', 'Vwo', 'Havo', 'Vmbo g/t', 'Vmbo-k',
       'Vmbo-b', 'Totaal vavo', 'Vavo vwo', 'Vavo havo', 'Vavo vmbo-t',
       'Totaal mbo (incl. extranei)', 'Entreeopleiding (incl.extranei)',
       'Niveau 2 (inclusief extranei)', 'Niveau 3 (inclusief extranei)',
       'Niveau 4 (inclusief extranei)', 'Hbo-associate degree', 'Hbo-bachelor',
       'Hbo-master/vervolgopleiding', 'Wo-bachelor', 'Wo-master'],
      dtype='object', name='Onderwijssoort')

In [49]:
tm.assert_index_equal(test_reset_known_index.index, indexed_df.index)

In [50]:
changed_dtype_df = indexed_df.astype("int64")
changed_dtype_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, Totaal voortgezet onderwijs (vo) to Wo-master
Data columns (total 23 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Nederland                                 20 non-null     int64
 1   Noord-Nederland (LD)                      20 non-null     int64
 2   Oost-Nederland (LD)                       20 non-null     int64
 3   West-Nederland (LD)                       20 non-null     int64
 4   Zuid-Nederland (LD)                       20 non-null     int64
 5   Niet in te delen (LD)                     20 non-null     int64
 6   Groningen (PV)                            20 non-null     int64
 7   Fryslân (PV)                              20 non-null     int64
 8   Drenthe (PV)                              20 non-null     int64
 9   Overijssel (PV)                           20 non-null     int64
 10  Flevoland (PV)                            20 non-null     int64
 11  Gelderland (PV)                           20 non-null     int64
 12  Utrecht (PV)                              20 non-null     int64
 13  Noord-Holland (PV)                        20 non-null     int64
 14  Zuid-Holland (PV)                         20 non-null     int64
 15  Zeeland (PV)                              20 non-null     int64
 16  Noord-Brabant (PV)                        20 non-null     int64
 17  Limburg (PV)                              20 non-null     int64
 18  Niet in te delen (PV)                     20 non-null     int64
 19  Vier grootste gemeenten                   20 non-null     int64
 20  Meer dan 100 000 inwoners (exclusief G4)  20 non-null     int64
 21  Minder dan 100 000 inwoners               20 non-null     int64
 22  Niet in te delen                          20 non-null     int64
dtypes: int64(23)
memory usage: 3.8+ KB

In [51]:
def change_dtype_columns(df, dtype):
    changed_df = df.astype(dtype)
    return changed_df

test_change_dtype_columns = change_dtype_columns(indexed_df, "int64")
test_change_dtype_columns.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, Totaal voortgezet onderwijs (vo) to Wo-master
Data columns (total 23 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Nederland                                 20 non-null     int64
 1   Noord-Nederland (LD)                      20 non-null     int64
 2   Oost-Nederland (LD)                       20 non-null     int64
 3   West-Nederland (LD)                       20 non-null     int64
 4   Zuid-Nederland (LD)                       20 non-null     int64
 5   Niet in te delen (LD)                     20 non-null     int64
 6   Groningen (PV)                            20 non-null     int64
 7   Fryslân (PV)                              20 non-null     int64
 8   Drenthe (PV)                              20 non-null     int64
 9   Overijssel (PV)                           20 non-null     int64
 10  Flevoland (PV)                            20 non-null     int64
 11  Gelderland (PV)                           20 non-null     int64
 12  Utrecht (PV)                              20 non-null     int64
 13  Noord-Holland (PV)                        20 non-null     int64
 14  Zuid-Holland (PV)                         20 non-null     int64
 15  Zeeland (PV)                              20 non-null     int64
 16  Noord-Brabant (PV)                        20 non-null     int64
 17  Limburg (PV)                              20 non-null     int64
 18  Niet in te delen (PV)                     20 non-null     int64
 19  Vier grootste gemeenten                   20 non-null     int64
 20  Meer dan 100 000 inwoners (exclusief G4)  20 non-null     int64
 21  Minder dan 100 000 inwoners               20 non-null     int64
 22  Niet in te delen                          20 non-null     int64
dtypes: int64(23)
memory usage: 3.8+ KB

In [52]:
tm.assert_frame_equal(test_change_dtype_columns, changed_dtype_df)

In [53]:
changed_dtype_df.head(23)

,Nederland,Noord-Nederland (LD),Oost-Nederland (LD),West-Nederland (LD),Zuid-Nederland (LD),Niet in te delen (LD),Groningen (PV),Fryslân (PV),Drenthe (PV),Overijssel (PV),...,Noord-Holland (PV),Zuid-Holland (PV),Zeeland (PV),Noord-Brabant (PV),Limburg (PV),Niet in te delen (PV),Vier grootste gemeenten,Meer dan 100 000 inwoners (exclusief G4),Minder dan 100 000 inwoners,Niet in te delen
Onderwijssoort,,,,,,,,,,,,,,,,,,,,,
Totaal voortgezet onderwijs (vo),167410,16200,38620,78840,33410,340,4700,6490,5020,12860,...,26400,34640,3600,24480,8930,340,18340,37650,111070,340
Vwo,35610,2830,6970,18980,6760,70,960,1060,810,2070,...,6650,7750,610,4920,1840,70,4660,8330,22550,70
Havo,45410,4340,10450,21400,9140,90,1230,1830,1280,3420,...,7400,8910,1060,6760,2380,90,4530,10320,30470,90
Vmbo g/t,47340,4760,11140,21490,9840,120,1330,1940,1490,3910,...,6950,9930,1070,7290,2540,120,4660,10710,31850,120
Vmbo-k,24870,2840,6590,10500,4890,40,750,1080,1010,2230,...,3460,4880,550,3530,1370,40,2670,5280,16870,40
Vmbo-b,14180,1430,3470,6470,2790,20,430,580,430,1230,...,1940,3180,310,1990,800,20,1820,3010,9330,20
Totaal vavo,5250,460,1200,2560,1010,10,150,190,130,350,...,990,1060,90,690,320,10,780,1480,2980,10
Vavo vwo,1560,160,340,770,290,0,50,70,40,100,...,340,260,30,210,90,0,250,410,900,0
Vavo havo,3050,270,700,1470,600,10,90,100,80,200,...,550,640,60,410,190,10,470,850,1730,10
Vavo vmbo-t,640,40,160,330,110,0,10,20,10,50,...,100,170,10,70,50,0,70,220,350,0
Totaal mbo (incl. extranei),152040,17960,37200,66260,29820,800,5610,7130,5230,12550,...,21920,30910,3530,21380,8440,800,17330,34630,99280,800
Entreeopleiding (incl.extranei),11500,1210,2290,6000,1900,100,350,520,340,710,...,2090,3000,230,1350,550,100,2370,2900,6130,100
Niveau 2 (inclusief extranei),33950,3770,8470,15420,6140,140,1240,1430,1110,2790,...,5150,7270,790,4420,1720,140,4630,7680,21500,140
Niveau 3 (inclusief extranei),34040,4500,9030,13580,6760,170,1340,1910,1250,3070,...,4430,6330,950,4840,1930,170,2750,7020,24110,170
Niveau 4 (inclusief extranei),72540,8480,17400,31260,15020,390,2670,3270,2530,5980,...,10250,14300,1560,10780,4240,390,7580,17030,47550,390
Hbo-associate degree,5120,550,1160,1860,1500,50,160,220,170,350,...,400,1000,150,1260,240,50,460,1290,3330,50
Hbo-bachelor,66450,7060,14440,28500,14130,2330,3300,2340,1420,5160,...,9670,12590,1060,10240,3890,2330,10340,19910,33870,2330
Hbo-master/vervolgopleiding,4670,500,820,2040,870,440,230,190,80,300,...,720,870,50,650,220,440,1080,1340,1820,440
Wo-bachelor,41640,4020,5850,22440,6570,2760,3440,330,250,1660,...,7580,10490,250,3960,2610,2760,11580,15950,11340,2760
Wo-master,51590,3830,6880,26660,7360,6870,3080,470,280,1790,...,9580,11930,160,4980,2390,6870,15950,17060,11710,6870

In [54]:
education_kind = ["vo", "vo", "vo", "vo", "vo", "vo", "vavo", "vavo", "vavo", "vavo", "mbo", "mbo", "mbo", "mbo", "mbo", "hbo", "hbo", "hbo", "wo", "wo"]
changed_dtype_df.insert(0, "Globale onderwijssoort", education_kind, allow_duplicates=True)

In [55]:
global_education_df = changed_dtype_df
global_education_df.head(23)

,Globale onderwijssoort,Nederland,Noord-Nederland (LD),Oost-Nederland (LD),West-Nederland (LD),Zuid-Nederland (LD),Niet in te delen (LD),Groningen (PV),Fryslân (PV),Drenthe (PV),...,Noord-Holland (PV),Zuid-Holland (PV),Zeeland (PV),Noord-Brabant (PV),Limburg (PV),Niet in te delen (PV),Vier grootste gemeenten,Meer dan 100 000 inwoners (exclusief G4),Minder dan 100 000 inwoners,Niet in te delen
Onderwijssoort,,,,,,,,,,,,,,,,,,,,,
Totaal voortgezet onderwijs (vo),vo,167410,16200,38620,78840,33410,340,4700,6490,5020,...,26400,34640,3600,24480,8930,340,18340,37650,111070,340
Vwo,vo,35610,2830,6970,18980,6760,70,960,1060,810,...,6650,7750,610,4920,1840,70,4660,8330,22550,70
Havo,vo,45410,4340,10450,21400,9140,90,1230,1830,1280,...,7400,8910,1060,6760,2380,90,4530,10320,30470,90
Vmbo g/t,vo,47340,4760,11140,21490,9840,120,1330,1940,1490,...,6950,9930,1070,7290,2540,120,4660,10710,31850,120
Vmbo-k,vo,24870,2840,6590,10500,4890,40,750,1080,1010,...,3460,4880,550,3530,1370,40,2670,5280,16870,40
Vmbo-b,vo,14180,1430,3470,6470,2790,20,430,580,430,...,1940,3180,310,1990,800,20,1820,3010,9330,20
Totaal vavo,vavo,5250,460,1200,2560,1010,10,150,190,130,...,990,1060,90,690,320,10,780,1480,2980,10
Vavo vwo,vavo,1560,160,340,770,290,0,50,70,40,...,340,260,30,210,90,0,250,410,900,0
Vavo havo,vavo,3050,270,700,1470,600,10,90,100,80,...,550,640,60,410,190,10,470,850,1730,10
Vavo vmbo-t,vavo,640,40,160,330,110,0,10,20,10,...,100,170,10,70,50,0,70,220,350,0
Totaal mbo (incl. extranei),mbo,152040,17960,37200,66260,29820,800,5610,7130,5230,...,21920,30910,3530,21380,8440,800,17330,34630,99280,800
Entreeopleiding (incl.extranei),mbo,11500,1210,2290,6000,1900,100,350,520,340,...,2090,3000,230,1350,550,100,2370,2900,6130,100
Niveau 2 (inclusief extranei),mbo,33950,3770,8470,15420,6140,140,1240,1430,1110,...,5150,7270,790,4420,1720,140,4630,7680,21500,140
Niveau 3 (inclusief extranei),mbo,34040,4500,9030,13580,6760,170,1340,1910,1250,...,4430,6330,950,4840,1930,170,2750,7020,24110,170
Niveau 4 (inclusief extranei),mbo,72540,8480,17400,31260,15020,390,2670,3270,2530,...,10250,14300,1560,10780,4240,390,7580,17030,47550,390
Hbo-associate degree,hbo,5120,550,1160,1860,1500,50,160,220,170,...,400,1000,150,1260,240,50,460,1290,3330,50
Hbo-bachelor,hbo,66450,7060,14440,28500,14130,2330,3300,2340,1420,...,9670,12590,1060,10240,3890,2330,10340,19910,33870,2330
Hbo-master/vervolgopleiding,hbo,4670,500,820,2040,870,440,230,190,80,...,720,870,50,650,220,440,1080,1340,1820,440
Wo-bachelor,wo,41640,4020,5850,22440,6570,2760,3440,330,250,...,7580,10490,250,3960,2610,2760,11580,15950,11340,2760
Wo-master,wo,51590,3830,6880,26660,7360,6870,3080,470,280,...,9580,11930,160,4980,2390,6870,15950,17060,11710,6870